version: '3.4'
services:
  hamster:
    build: .
    volumes:
      - ./database.db:/app/database.db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hamster
    ports:
      - "9000:80"
